### ISSUE TITLE
Snap license in the store listing does not inherit the `license` field from the snap

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [canonical-websites/snapcraft.io#1710]
### Expected behaviour
When the snap sets the `license` field and the metadata has not overridden the value of the `license` field is applied to the snap's "License" field in the store listing

### Steps to reproduce the problem
1. Set up a snap repository with the `license` field set
1. Set up BSI with the repository
1. Browse the snap listing page after the snap is published

### Specs

- _URL:_ https://snapcraft.io/_snap_identifier_/listing
- _Operating system:_ Ubuntu 18.04 AMD64
- _Browser:_ Mozilla Firefox 65.0.1

**Comment by anthonydillon** [comment]
I would suggest leaving this in New issues until the investigation has been done. Keeps in coming up regularly in stand up.

**Comment by tbille** [comment]
This has been discussed with the store and snacpraft team.
Both teams are working on a solution that should fix this issue. snapcraft.io will implement soon a way to update the metadata once it has been updated on the listing page.
More coming soon.

**Comment by soumyaDghosh** [comment]
I can confirm, that it's been 3 years now and the license, still isn't adopted from the snap manifest.

**Comment by sed-i** [comment]
This is still an issue. Example: https://snapcraft.io/nushell.

**Comment by brlin-tw** [comment]
No longer reproducible at my end.
